{
	"version": 1615536446,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/ground-sheet0.png",
		"images/fruit-sheet0.png",
		"images/enemy-sheet0.png",
		"images/rightbutton-sheet0.png",
		"images/leftbutton-sheet0.png",
		"images/jumpbutton-sheet0.png",
		"images/enemyef.png",
		"images/menubutton-sheet0.png",
		"images/resetbutton-sheet0.png",
		"images/bg-sheet0.png",
		"images/tiledbackground.png",
		"images/quizpoint-sheet0.png",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"media/mattoglseby - 2.m4a",
		"media/mattoglseby - 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}